general:
  experiment_name: "ComprehensiveCustomLoadersTestGPT2"
  output_dir: "./benchmarks_output_comprehensive_custom"
  random_seed: 42

models:
  - name: "gpt2-via-custom-script"
    framework: "custom_script"
    script_path: "src/benchmark/custom_loader_scripts/my_model_functions.py"
    function_name: "load_local_hf_model_example"
    checkpoint: "gpt2"
    torch_dtype_str: "float32"
    quantization: null

tasks:
  - name: "GSM8K (Reasoning Text Analysis)"
    type: "math_reasoning_generation"
    description: "Grade school math problems. Evaluates the textual properties of the generated reasoning steps and the final answer."
    datasets:
      - name: "my_custom_csv_for_gsm8k_test"
        source_type: "custom_script"
        script_path: "src/benchmark/custom_loader_scripts/my_dataset_functions.py"
        function_name: "load_simple_csv_data"
        split: "train"
        max_samples: 10
        dataset_specific_fields:
          input: "text_content"
          target: "category_label"
        script_args:
          data_file_path: "src/benchmark/custom_loader_scripts/data/sample_train_dataset.csv"

    handler_options:
      prompt_builder_type: "default"
      prompt_template: "Solve the following math problem. Show your reasoning step-by-step. Conclude with the final numerical answer formatted as ####<number>.\n\nProblem: {input_text}\n\nSolution:"
      postprocessor_key: "gsm8k" # IMPORTANT: This extracts the final number for exact_match

    evaluation_metrics:
      - name: "custom_script"
        options:
          metric_script_path: "src/benchmark/custom_loader_scripts/my_metrics_functions.py"
          metric_init_function_name: "init_avg_pred_length_state"
          metric_update_function_name: "update_avg_pred_length_state"
          metric_result_function_name: "result_avg_pred_length"
          metric_script_args:
            result_key_name: "custom_avg_words"
      - name: "rouge"
        options:
          metrics: ["rouge1"]
          stats: ["f"]

evaluation:
  log_interval: 1

reporting:
  enabled: true
  format: "json"

advanced:
  batch_size: 2
  generate_max_length: 128
  truncation: true
  padding: true