# ============================
# General Configuration
# ============================

general:
  experiment_name: "Gemma_Benchmark_2025"
  output_dir: "./benchmarks"
  random_seed: 42

# ============================
# Benchmark Tasks Configuration
# ============================

tasks:
  - name: "MMLU"
    type: "classification"
    description: "Massive Multitask Language Understanding"
    datasets:
      - name: "mmlu"
        type: "classification"
        splits: ["train", "validation"]
    evaluation_metrics: [accuracy, f1_score, perplexity]

  - name: "GSM8K"
    type: "generation"
    description: "Math dataset with problem-solving tasks"
    datasets:
      - name: "gsm8k"
        type: "generation"
        splits: ["train", "validation"]
    evaluation_metrics: [accuracy, execution_time]

# ============================
# Models Configuration
# ============================

models:
  - name: "gemma-7b"
    variant: "gemma"
    size: "7B"
    framework: "huggingface"
    checkpoint: "gemma-7b-checkpoint"
    quantization: "4bit"
    offloading: true

  - name: "gemma-13b"
    variant: "gemma"
    size: "13B"
    framework: "huggingface"
    checkpoint: "gemma-13b-checkpoint"
    quantization: "8bit"
    offloading: true

  - name: "llama-2-7b"
    variant: "llama"
    size: "7B"
    framework: "huggingface"
    checkpoint: "llama-2-7b-checkpoint"
    quantization: "4bit"
    offloading: true

  - name: "mistral-7b"
    variant: "mistral"
    size: "7B"
    framework: "huggingface"
    checkpoint: "mistral-7b-checkpoint"
    quantization: "4bit"
    offloading: true

# ============================
# Model Parameters Configuration
# ============================

model_parameters:
  batch_size: 4
  max_input_length: 512
  max_output_length: 512
  temperature: 0.7
  top_p: 0.9
  top_k: 50

# ============================
# Evaluation Configuration
# ============================

evaluation:
  batch_size: 16
  log_interval: 100

# ============================
# Results and Reporting
# ============================

reporting:
  enabled: true
  format: "pdf"
  leaderboard_enabled: true
  generate_visuals:
    charts: true
    tables: true
    save_plots: true
  output_dir: "./reports"

# ============================
# Advanced Settings
# ============================

advanced:
  enable_multi_gpu: false
  use_tpu: false
  distributed_training: false